### ISSUE TITLE
why different output of the same image in two different test?

### ISSUE THREAD

**Issue by guoxiaolu** [BestiVictory/ILGnet#4]
I have used the pretrained model you offered(https://pan.baidu.com/s/1slMv4yp), and just modify the model name and image name of your test code. But in two different test, I have got different output results, for example, {good:0.6, bad:0.4} {good:0.4, bad:0.6}. It makes me confused and expects your answers~

**Comment by BestiVictory** [comment]
deploy.protxt  consists of some initialize information , you could drop out these parts.
such as
 weight_filler {
      type: "xavier"
 }
bias_filler {
      type: "constant"
      value: 0.2
 }

**Comment by guoxiaolu** [comment]
Thank you very much, I will check it

**Comment by FormatFish** [comment]
@BestiVictory  I have same problem , and I try your method, but finally the score is always 0.5 whatever picture is.

**Comment by guoxiaolu** [comment]
Unfortunately, I didn't get the correct result, maybe other reasons. Finally, we reimplemented Adobe's paper, and get a good result.@FormatFish, you can make a try, it's a regression problem and Adobe used multi-task regression to solve it.
